---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
      MOLECULE_DOCKER_COMMAND: /sbin/init
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test
